# Google Custom Search Engine Configuration
# Uses ${VAR} placeholders resolved from environment variables

api_key: ${GOOGLE_API_KEY}
cx: ${GOOGLE_CX}

# Search parameters
max_results: 100
results_per_page: 10
timeout_seconds: 30

# Domain boosting for authority scoring
authority_domains:
  - .gov.br
  - .saude.gov.br
  - ans.gov.br
  - www.in.gov.br
  - www.planalto.gov.br

# Keyword boosting for specificity
specificity_keywords:
  high:
    - "RN 259"
    - "RN 465"
    - "Resolução Normativa"
    - "TISS"
    - "TUSS"
    - "Anexo"
    - "Lei Federal"
  medium:
    - "Regulamentação"
    - "Portaria"
    - "Instrução Normativa"
  low:
    - "Notícia"
    - "Artigo"
    - "Blog"

# Content type preferences (for scoring)
type_preferences:
  pdf: 1.5
  zip: 1.3
  html: 1.0

# Anchorability markers (presence boosts score)
anchor_markers:
  - "Art."
  - "Artigo"
  - "Cap."
  - "Capítulo"
  - "Anexo"
  - "Tabela"
  - "Seção"

# Language preference
language: pt-BR

